import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "./component/authProvider/authProvider";
import NavBar from "./component/navbar/navbar";
import Footer from "./component/footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "NextJS App",
    description: "Generated by Do Duc Hieu",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <AuthProvider>
                    <NavBar />
                    {children}
                    <Footer />
                </AuthProvider>
            </body>
        </html>
    );
}
